package net.pxstudios.minelib.board;

public enum BoardFlag {

    USE_DISABLED_WORLD_SYSTEM,

    VIEW_ON_PLAYER_JOIN,

    REMOVE_ON_PLAYER_JOIN,

    REMOVE_ON_CHANGED,

    USE_GLOBAL_PRESETS,

    WITH_AUTOMATICALLY_STATIC_LINES_COLORIZE,
}
